logging:
  level:
    root: info
    org:
      hibernate.SQL: error
      springframework:
        security=DEBUG:

  file:
    path: logs/storage.log

spring:
  datasource:
    password: password
    url: jdbc:mysql://localhost:3306/phoestorage
    username: phoestorage

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: false

    properties:
      hibernate:
        format_sql: true

server:
  root: C:\storage